import express from 'express';
import { prisma } from '../../db.js'
import { reverse } from 'node:dns';
import { Performance } from 'node:perf_hooks';


const router = express.Router();

router.get('/', (req, res) => {
  res.send('Nodes route is working!');
});

// Create a folder
router.post('/folder/create', async (req, res)=>{
  const {userId, name, parentId} = req.body
  const color = req.body.color?.toUpperCase()
  const type = req.body.type?.toUpperCase()
  if(!userId || !name || type !== 'FOLDER' || !color) return res.status(400).json({ message: ('Incomplete Details!') })

  try{
  const node = await prisma.node.create({
    data: { userId, name, type, color, parentId }
  })
    return res.status(201).json({ message: ('Folder has been created successfully!')})
  }
  catch(e){
    return res.status(400).json({ message: e || ('Data is invalid')})
  }
})

// Delete a folder
router.delete('/folder/delete', async(req, res)=>{
  const {id, userId} = req.body
  const type = req.body.type?.toUpperCase()
  if(!id || !userId || !type) return res.status(400).json({ message: ('Incomplete Details!') })

  try{
      const node = await prisma.$executeRaw`
      WITH RECURSIVE descendants AS(
        SELECT id FROM "Node"
        WHERE id = ${id}

        UNION All

        SELECT n.id FROM "Node" n
        JOIN descendants d
        ON n."parentId" = d.id
      )

      DELETE FROM "Node"
      WHERE id IN (
        SELECT id FROM descendants
      )
      `
      return res.status(200).json({ message: (`Folder with id: ${id} has been deleted!`)})
    }
    catch(e){
      res.status(500).json({ message: e.message || ('Something went wrong!')})
    }
})


// Create a file
router.post('/file/create', async(req, res)=>{
  const {userId, name, parentId} = req.body
  const ext = req.body.ext?.toUpperCase()
  const type = req.body.type?.toUpperCase()

  if(!userId || !name || type !== 'FILE') return res.status(400).json({ message: ('Incomplete Details!') })

  try{
    const node = await prisma.node.create({
      data: { userId, name, type, ext, parentId}
    })
    return res.status(201).json({ message: ('File has been created successfully!')})
  }
  catch(e){
    return res.status(400).json({ message: e || ('Data is invalid')})
  }
})

// Delete a file
router.delete('/file', async(req, res)=>{
  const { id, userId, type } = req.body

  if(!id || !userId || !type) return res.status(400).json({ message: ('Incomplete Details!')})

  try{
    const node = await prisma.user.delete({ where: {id: id, userId: userId, type: type}})
    return res.status(204).json({ message: (`File with id: ${id} has been successfully deleted`)})
  }
  catch(e){
    res.status(400).json({ message: e || ('Something went wrong')})
  }
})


// Get Path from Root
router.get('/:id', async(req, res)=>{
  const { id } = req.params

  const startTime = process.hrtime.bigint();
  const path = []
  let curId = id

  while (true) {
    try{
      const node = await prisma.node.findUnique({ where: {id: curId}})
      path.push({id: node.id, name: node.name})
      curId = node.parentId
    }
    catch(e){
      return res.status(400).json({ message: e || ('Error while tracing path')})
    }
    if(!curId) break
  }

  const endTime = process.hrtime.bigint();
  const timeTakenMs = Number(endTime - startTime) / 1e6;
  console.log(`Path Generated by Naive Query in ${timeTakenMs.toFixed(4)} ms`);

  path.reverse()

  return res.status(200).json({ path, message: ('Path generated')})
})


export default router;